import { Inter } from "next/font/google";
import "./globals.css";
import AdSense from "@/components/AdSense";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
      <AdSense pId={"ca-pub-8034519108259358"}/>
    </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
