import { Inter } from "next/font/google";
import "./globals.css";
import Head from 'next/head';
import Script from "next/script";
import GoogleAdsense from "@/components/GoogleAdsense";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="tr">
      <Head>
     {/*   <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <script>
          {`(adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-8034519108259358",
            enable_page_level_ads: true
          });`}
        </script>*/}

        {/*  <Script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></Script>
           eslint-disable-next-line @next/next/inline-script-id
          <Script
              dangerouslySetInnerHTML={{
                  __html: `(adsbygoogle = window.adsbygoogle || []).push({
                      google_ad_client: "ca-pub-8034519108259358",
                      enable_page_level_ads: true
                    });`,
              }}
          ></Script>*/}
        <title>Test</title>
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8034519108259358"
                  crossOrigin="anonymous"></script>
      </Head>
      <body>{children}</body>
      <GoogleAdsense pId="8034519108259358" />

      </html>
  );
}
