import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AdSense from "../../components/AdSense";
import Head from "next/head";
import Script from "next/script";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
          <script
              dangerouslySetInnerHTML={{
                  __html: `(adsbygoogle = window.adsbygoogle || []).push({
                      google_ad_client: "ca-pub-8034519108259358",
                      enable_page_level_ads: true
                    });`,
              }}
          />
        {/*<AdSense pId="ca-pub-8034519108259358"/>*/}
          {/*<Script*/}
          {/*    async*/}
          {/*    src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8034519108259358`}*/}
          {/*    crossOrigin='anonymous'*/}
          {/*    strategy='afterInteractive'*/}
          {/*/>*/}

      {/*    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8034519108259358"
                  crossOrigin="anonymous"></script>*/}
          <title></title>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
